from unittest import TestCase

from systemofrecord.services import ingest_queue
from system_of_record_message_fixtures import valid_message_without_tags
from datatypes.exceptions import DataDoesNotMatchSchemaException
from system_of_record_message_fixtures import invalid_message_without_object


class IngestQueueConsumerTestCase(TestCase):
   pass